CREATE DATABASE coffee;
USE coffee;

CREATE TABLE coffee (
    transaction_id INT PRIMARY KEY,
    transaction_date DATE,
    transaction_time TIME,
    transaction_qty INT,
    store_id INT,
    store_location VARCHAR(50),
    product_id INT,
    unit_price DECIMAL(5,2),
    product_category VARCHAR(50),
    product_type VARCHAR(50),
    product_detail VARCHAR(100)
);
SELECT*FROM coffee;

-- adding new column

ALTER TABLE coffee
ADD COLUMN product_size VARCHAR(20);

-- Updating product_size Column
SET SQL_SAFE_UPDATES=0;
UPDATE coffee
SET product_size = CASE
    WHEN product_detail LIKE '%Rg' THEN 'Regular'
    WHEN product_detail LIKE '%Lg' THEN 'Large'
    WHEN product_detail LIKE '%Sm' THEN 'Small'
    ELSE 'Not Defined'
END;

-- Removing Size Abbreviations from product_detail

UPDATE coffee
SET product_detail = TRIM(
    REPLACE(
        REPLACE(
            REPLACE(product_detail, ' Rg', ''),
            ' Lg', ''),
        ' Sm', '')
);

-- 1.Total Transactions & Revenue

SELECT 
    COUNT(*) AS total_transactions,
    SUM(transaction_qty) AS total_items_sold,
    SUM(transaction_qty * unit_price) AS total_revenue
FROM coffee;

-- 2.Revenue by Store
SELECT store_location, 
       SUM(transaction_qty * unit_price) AS revenue,
       COUNT(*) AS total_transactions,
       SUM(transaction_qty) AS total_items_sold
FROM coffee
GROUP BY store_location
ORDER BY revenue DESC;

-- 3.List the top 10 best-selling products based on quantity sold

SELECT product_detail, 
       SUM(transaction_qty) AS total_qty_sold,
       SUM(transaction_qty * unit_price) AS total_revenue
FROM coffee
GROUP BY product_detail
ORDER BY total_qty_sold DESC
LIMIT 10;

-- 4.	Calculate total revenue, average price, and total quantity sold for each product category.

SELECT product_category,
SUM(transaction_qty * unit_price) AS total_revenue,
AVG(unit_price) AS avg_price,
SUM(transaction_qty) AS total_qty_sold
FROM coffee
GROUP BY product_category
ORDER BY total_revenue DESC;

-- 5.	Determine the peak sales hours of the day based on revenue and transaction count.

SELECT HOUR(transaction_time) AS hour_of_day,
       COUNT(*) AS num_transactions,
       SUM(transaction_qty * unit_price) AS revenue
FROM coffee
GROUP BY hour_of_day
ORDER BY hour_of_day;

-- 6.	Find the average transaction value for each store location

SELECT store_location,
       AVG(transaction_qty * unit_price) AS avg_transaction_value
FROM coffee
GROUP BY store_location
ORDER BY avg_transaction_value DESC;

-- 7.	Identify the most frequently purchased products in each store.
SELECT store_location, product_detail,
       COUNT(*) AS purchase_count,
       SUM(transaction_qty) AS total_qty
FROM coffee
GROUP BY store_location, product_detail
ORDER BY store_location, total_qty DESC;

-- 8.	Find the top 10 high-value products based on revenue per unit sold.

SELECT product_detail,
       SUM(transaction_qty * unit_price)/SUM(transaction_qty) AS revenue_per_unit
FROM coffee
GROUP BY product_detail
ORDER BY revenue_per_unit DESC
LIMIT 10;

-- 9.	List the 10 least-selling products based on total quantity sold.

SELECT product_detail, 
       SUM(transaction_qty) AS total_qty_sold,
       SUM(transaction_qty * unit_price) AS total_revenue
FROM coffee
GROUP BY product_detail
ORDER BY total_qty_sold ASC
LIMIT 10;

-- 10.	Analyze the daily revenue trend over time.

SELECT transaction_date,
       SUM(transaction_qty * unit_price) AS daily_revenue,
       COUNT(*) AS num_transactions
FROM coffee
GROUP BY transaction_date
ORDER BY transaction_date;

-- 11.	Find total revenue generated by each product type across different stores

SELECT store_location,
       product_type,
       SUM(transaction_qty * unit_price) AS revenue
FROM coffee
GROUP BY store_location, product_type
ORDER BY store_location,revenue DESC;

-- 12.	Calculate hourly revenue for each store to understand time-based performance.

SELECT store_location, HOUR(transaction_time) AS hour_of_day,
       SUM(transaction_qty * unit_price) AS revenue
FROM coffee
GROUP BY store_location, hour_of_day
ORDER BY store_location, hour_of_day;

-- 13.	Identify the top revenue-generating store overall.

SELECT store_location,
       SUM(transaction_qty * unit_price) AS total_revenue
FROM coffee
GROUP BY store_location
ORDER BY total_revenue DESC
LIMIT 1;

-- 14.	Determine which product has generated the highest total revenue overall.

SELECT product_detail,
       SUM(transaction_qty * unit_price) AS total_revenue
FROM coffee
GROUP BY product_detail
ORDER BY total_revenue
LIMIT 1;

-- 15.	Find the average unit price for each product category.

SELECT product_category,
       AVG(unit_price) AS avg_unit_price
FROM coffee
GROUP BY product_category
ORDER BY avg_unit_price ASC;

-- 16.	Calculate each product category’s revenue contribution percentage to total sales.

SELECT product_category,
       SUM(transaction_qty * unit_price) AS revenue,
       ROUND(SUM(transaction_qty * unit_price)*100 / 
             (SELECT SUM(transaction_qty * unit_price) FROM coffee), 2) AS revenue_percent
FROM coffee
GROUP BY product_category
ORDER BY revenue_percent DESC;
